
# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/dcb2230a-a81e-4f45-aa34-577aa7900e30/transcription
Content-Type: application/json

{
  "prompt": "features nextjs 13.0"
}

###

# @name generate-ia-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "dcb2230a-a81e-4f45-aa34-577aa7900e30",
  "temperature": 0.5,
  "template": "Gere um resumo sucinto da transcrição do vídeo informado a seguir: '''{transcription}'''",
}